CREATE TABLE if not exists prj_log (
    loguui CHARACTER VARYING(32) NOT NULL UNIQUE,
    ip CHARACTER VARYING(32) NOT NULL,
    useruuid CHARACTER VARYING(32) NOT NULL,
    tstamp bigint NOT NULL UNIQUE,
    logurl CHARACTER VARYING(32) NOT NULL UNIQUE,
    datarequest CHARACTER VARYING(32) NOT NULL UNIQUE,
    dataresponse CHARACTER VARYING(32) NOT NULL UNIQUE
);

